# Generated by Django 3.0.5 on 2020-04-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0002_auto_20170228_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='@@', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='visual',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='interest',
            name='key',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='event_id',
            field=models.CharField(default='me', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='visual',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='ytoken',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='promoted',
            name='name',
            field=models.CharField(default='@#', max_length=2),
        ),
    ]
