from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path

from .views import *

urlpatterns = [ # 'efforia.views',   
    path('', main),
    path('mosaic', mosaic),
    path('config', config),
    path('profile', profile),
    path('basketclean', basketclean),
    path('basket', basket),
    path('photo', photo),
    path('appearance', appearance),
    path('options', options),
    path('place', place),
    path('password', password),
    path('integrations', integrations),
    path('enter', authenticate),
    path('leave', leave),
    path('delete', delete),
    path('userid', ids),
    path('search', search),
    path('explore', search),
    path('known', explore),
    path('activity', activity),
    path('following', following),
    path('follow', follow),
    path('unfollow', unfollow),
    path('twitter/post', twitter_post),
    path('facebook/post', facebook_post),
    path('facebook/eventcover', facebook_eventcover),
    path('facebook/event', facebook_event),
    path('participate', participate),
    path('tutorial', tutorial),
    path('pagseguro/cart', pagsegurocart),
    path('pagseguro', pagseguro),
    path('paypal/cart', paypalcart),
    path('paypal', paypal),
    path('pages', page),
    path('pageview', pageview),
    path('pageedit', pageedit),
    path('discharge', discharge),
    path('recharge', recharge),
    path('balance', balance),
    path('deadlines', deadlines),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
